var productRotationData_1471761633144 = {
    "custom": {
        "contexMenu": {"items": [{"title": "", "data": "", "action": "URL_OPEN"}]}
    },
    "hotspots": null,
    "settings": {
        "preloader": {
            "type": "default",
            "image": 0,
            "color1": "#303030",
            "showStartButton": false,
            "showStartButtonMobile": false,
            "showLoadedImages": false
        },
        "control": {
            "maxZoomAuto": false,
            "mouseWheelZooms": false,
            "enableSwing": true,
            "reverseDrag": true,
            "zoomInStopsRotation": true,
            "switchToPanOnYmovement": true,
            "zoomSetsPan": false,
            "rotateOnClick": true,
            "dragSpeed": 0.5,
            "rotateOnMouseHover": false,
            "disableMouseControl": false,
            "clickUrlTarget": "_blank",
            "clickUrl": "",
            "maxZoom": 300,
            "touchPageScroll": false
        },
        "rotation": {
            "firstImage": 0,
            "rotatePeriod": 2,
            "bounce": false,
            "autoRestart": 0,
            "rotate": "false",
            "multilevel": {
                "disableDrag": false,
                "verticalSteps": 1,
                "verticalSensitivity": 20,
                "horizontalSteps": 1,
                "multidirectionalCycle": false,
                "traverse": 0,
                "reverseDrag": false
            },
            "disabledIfZoom": false,
            "rotateDirection": 1
        },
        "userInterface": {
            "showTogglePlayButton": false,
            "showMouseWheelToolTip": true,
            "showToggleRotateButton": "zoom",
            "showZoomButtons": false,
            "showZoombar": false,
            "showArrows": false,
            "showToggleFullscreenButton": true
        }
    },
    "images": [
        {"src": "images/asd000.png", "hotspots": {}},
        {"src": "images/asd001.png", "hotspots": {}},
        {"src": "images/asd002.png", "hotspots": {}},
        {"src": "images/asd003.png", "hotspots": {}},
        {"src": "images/asd004.png", "hotspots": {}},
        {"src": "images/asd005.png", "hotspots": {}},
        {"src": "images/asd006.png", "hotspots": {}},
        {"src": "images/asd007.png", "hotspots": {}},
        {"src": "images/asd008.png", "hotspots": {}},
        {"src": "images/asd009.png", "hotspots": {}},
        {"src": "images/asd010.png", "hotspots": {}},
        {"src": "images/asd011.png", "hotspots": {}},
        {"src": "images/asd012.png", "hotspots": {}},
        {"src": "images/asd013.png", "hotspots": {}},
        {"src": "images/asd014.png", "hotspots": {}},
        {"src": "images/asd015.png", "hotspots": {}},
        {"src": "images/asd016.png", "hotspots": {}},
        {"src": "images/asd017.png", "hotspots": {}},
        {"src": "images/asd018.png", "hotspots": {}},
        {"src": "images/asd019.png", "hotspots": {}},
        {"src": "images/asd020.png", "hotspots": {}},
        {"src": "images/asd021.png", "hotspots": {}},
        {"src": "images/asd022.png", "hotspots": {}},
        {"src": "images/asd023.png", "hotspots": {}},
        {"src": "images/asd024.png", "hotspots": {}},
        {"src": "images/asd025.png", "hotspots": {}},
        {"src": "images/asd026.png", "hotspots": {}},
        {"src": "images/asd027.png", "hotspots": {}},
        {"src": "images/asd028.png", "hotspots": {}},
        {"src": "images/asd029.png", "hotspots": {}},
        {"src": "images/asd030.png", "hotspots": {}},
        {"src": "images/asd031.png", "hotspots": {}},
        {"src": "images/asd032.png", "hotspots": {}},
        {"src": "images/asd033.png", "hotspots": {}},
        {"src": "images/asd034.png", "hotspots": {}},
        {"src": "images/asd035.png", "hotspots": {}},
        {"src": "images/asd036.png", "hotspots": {}},
        {"src": "images/asd037.png", "hotspots": {}},
        {"src": "images/asd038.png", "hotspots": {}},
        {"src": "images/asd039.png", "hotspots": {}},
        {"src": "images/asd040.png", "hotspots": {}},
        {"src": "images/asd041.png", "hotspots": {}},
        {"src": "images/asd042.png", "hotspots": {}},
        {"src": "images/asd043.png", "hotspots": {}},
        {"src": "images/asd044.png", "hotspots": {}},
        {"src": "images/asd045.png", "hotspots": {}},
        {"src": "images/asd046.png", "hotspots": {}},
        {"src": "images/asd047.png", "hotspots": {}},
        {"src": "images/asd048.png", "hotspots": {}},
        {"src": "images/asd049.png", "hotspots": {}},
        {"src": "images/asd050.png", "hotspots": {}},
        {"src": "images/asd051.png", "hotspots": {}},
        {"src": "images/asd052.png", "hotspots": {}},
        {"src": "images/asd053.png", "hotspots": {}},
        {"src": "images/asd054.png", "hotspots": {}},
        {"src": "images/asd055.png", "hotspots": {}},
        {"src": "images/asd056.png", "hotspots": {}},
        {"src": "images/asd057.png", "hotspots": {}},
        {"src": "images/asd058.png", "hotspots": {}},
        {"src": "images/asd059.png", "hotspots": {}},
        {"src": "images/asd060.png", "hotspots": {}},
        {"src": "images/asd061.png", "hotspots": {}},
        {"src": "images/asd062.png", "hotspots": {}},
        {"src": "images/asd063.png", "hotspots": {}},
        {"src": "images/asd064.png", "hotspots": {}},
        {"src": "images/asd065.png", "hotspots": {}},
        {"src": "images/asd066.png", "hotspots": {}},
        {"src": "images/asd067.png", "hotspots": {}},
        {"src": "images/asd068.png", "hotspots": {}},
        {"src": "images/asd069.png", "hotspots": {}},
        {"src": "images/asd070.png", "hotspots": {}},
        {"src": "images/asd071.png", "hotspots": {}},
        {"src": "images/asd072.png", "hotspots": {}},
        {"src": "images/asd073.png", "hotspots": {}},
        {"src": "images/asd074.png", "hotspots": {}},
        {"src": "images/asd075.png", "hotspots": {}},
        {"src": "images/asd076.png", "hotspots": {}},
        {"src": "images/asd077.png", "hotspots": {}},
        {"src": "images/asd078.png", "hotspots": {}},
        {"src": "images/asd079.png", "hotspots": {}},
        {"src": "images/asd080.png", "hotspots": {}},
        {"src": "images/asd081.png", "hotspots": {}},
        {"src": "images/asd082.png", "hotspots": {}},
        {"src": "images/asd083.png", "hotspots": {}},
        {"src": "images/asd084.png", "hotspots": {}},
        {"src": "images/asd085.png", "hotspots": {}},
        {"src": "images/asd086.png", "hotspots": {}},
        {"src": "images/asd087.png", "hotspots": {}},
        {"src": "images/asd088.png", "hotspots": {}},
        {"src": "images/asd089.png", "hotspots": {}},
        {"src": "images/asd090.png", "hotspots": {}},
        {"src": "images/asd091.png", "hotspots": {}},
        {"src": "images/asd092.png", "hotspots": {}},
        {"src": "images/asd093.png", "hotspots": {}},
        {"src": "images/asd094.png", "hotspots": {}},
        {"src": "images/asd095.png", "hotspots": {}},
        {"src": "images/asd096.png", "hotspots": {}},
        {"src": "images/asd097.png", "hotspots": {}},
        {"src": "images/asd098.png", "hotspots": {}},
        {"src": "images/asd099.png", "hotspots": {}},
        {"src": "images/asd100.png", "hotspots": {}},
        {"src": "images/asd101.png", "hotspots": {}},
        {"src": "images/asd102.png", "hotspots": {}},
        {"src": "images/asd103.png", "hotspots": {}},
        {"src": "images/asd104.png", "hotspots": {}},
        {"src": "images/asd105.png", "hotspots": {}},
        {"src": "images/asd106.png", "hotspots": {}},
        {"src": "images/asd107.png", "hotspots": {}},
        {"src": "images/asd108.png", "hotspots": {}},
        {"src": "images/asd109.png", "hotspots": {}},
        {"src": "images/asd110.png", "hotspots": {}},
        {"src": "images/asd111.png", "hotspots": {}},
        {"src": "images/asd112.png", "hotspots": {}},
        {"src": "images/asd113.png", "hotspots": {}},
        {"src": "images/asd114.png", "hotspots": {}},
        {"src": "images/asd115.png", "hotspots": {}},
        {"src": "images/asd116.png", "hotspots": {}},
        {"src": "images/asd117.png", "hotspots": {}},
        {"src": "images/asd118.png", "hotspots": {}},
        {"src": "images/asd119.png", "hotspots": {}},
        {"src": "images/asd120.png", "hotspots": {}},
        {"src": "images/asd121.png", "hotspots": {}},
        {"src": "images/asd122.png", "hotspots": {}},
        {"src": "images/asd123.png", "hotspots": {}},
        {"src": "images/asd124.png", "hotspots": {}},
        {"src": "images/asd125.png", "hotspots": {}},
        {"src": "images/asd126.png", "hotspots": {}},
        {"src": "images/asd127.png", "hotspots": {}},
        {"src": "images/asd128.png", "hotspots": {}},
        {"src": "images/asd129.png", "hotspots": {}},
        {"src": "images/asd130.png", "hotspots": {}},
        {"src": "images/asd131.png", "hotspots": {}},
        {"src": "images/asd132.png", "hotspots": {}},
        {"src": "images/asd133.png", "hotspots": {}},
        {"src": "images/asd134.png", "hotspots": {}},
        {"src": "images/asd135.png", "hotspots": {}},
        {"src": "images/asd136.png", "hotspots": {}},
        {"src": "images/asd137.png", "hotspots": {}},
        {"src": "images/asd138.png", "hotspots": {}},
        {"src": "images/asd139.png", "hotspots": {}},
        {"src": "images/asd140.png", "hotspots": {}},
        {"src": "images/asd141.png", "hotspots": {}},
        {"src": "images/asd142.png", "hotspots": {}},
        {"src": "images/asd143.png", "hotspots": {}},
        {"src": "images/asd144.png", "hotspots": {}},
        {"src": "images/asd145.png", "hotspots": {}},
        {"src": "images/asd146.png", "hotspots": {}},
        {"src": "images/asd147.png", "hotspots": {}},
        {"src": "images/asd148.png", "hotspots": {}},
        {"src": "images/asd149.png", "hotspots": {}},
        {"src": "images/asd150.png", "hotspots": {}},
        {"src": "images/asd151.png", "hotspots": {}},
        {"src": "images/asd152.png", "hotspots": {}},
        {"src": "images/asd153.png", "hotspots": {}},
        {"src": "images/asd154.png", "hotspots": {}},
        {"src": "images/asd155.png", "hotspots": {}},
        {"src": "images/asd156.png", "hotspots": {}},
        {"src": "images/asd157.png", "hotspots": {}},
        {"src": "images/asd158.png", "hotspots": {}},
        {"src": "images/asd159.png", "hotspots": {}},
        {"src": "images/asd160.png", "hotspots": {}},
        {"src": "images/asd161.png", "hotspots": {}},
        {"src": "images/asd162.png", "hotspots": {}},
        {"src": "images/asd163.png", "hotspots": {}},
        {"src": "images/asd164.png", "hotspots": {}},
        {"src": "images/asd165.png", "hotspots": {}},
        {"src": "images/asd166.png", "hotspots": {}},
        {"src": "images/asd167.png", "hotspots": {}},
        {"src": "images/asd168.png", "hotspots": {}},
        {"src": "images/asd169.png", "hotspots": {}},
        {"src": "images/asd170.png", "hotspots": {}},
        {"src": "images/asd171.png", "hotspots": {}},
        {"src": "images/asd172.png", "hotspots": {}},
        {"src": "images/asd173.png", "hotspots": {}},
        {"src": "images/asd174.png", "hotspots": {}},
        {"src": "images/asd175.png", "hotspots": {}},
        {"src": "images/asd176.png", "hotspots": {}},
        {"src": "images/asd177.png", "hotspots": {}},
        {"src": "images/asd178.png", "hotspots": {}},
        {"src": "images/asd179.png", "hotspots": {}},
        {"src": "images/asd180.png", "hotspots": {}},
        {"src": "images/asd181.png", "hotspots": {}},
        {"src": "images/asd182.png", "hotspots": {}},
        {"src": "images/asd183.png", "hotspots": {}},
        {"src": "images/asd184.png", "hotspots": {}},
        {"src": "images/asd185.png", "hotspots": {}},
        {"src": "images/asd186.png", "hotspots": {}},
        {"src": "images/asd187.png", "hotspots": {}},
        {"src": "images/asd188.png", "hotspots": {}},
        {"src": "images/asd189.png", "hotspots": {}},
        {"src": "images/asd190.png", "hotspots": {}},
        {"src": "images/asd191.png", "hotspots": {}},
        {"src": "images/asd192.png", "hotspots": {}},
        {"src": "images/asd193.png", "hotspots": {}},
        {"src": "images/asd194.png", "hotspots": {}},
        {"src": "images/asd195.png", "hotspots": {}},
        {"src": "images/asd196.png", "hotspots": {}},
        {"src": "images/asd197.png", "hotspots": {}},
        {"src": "images/asd198.png", "hotspots": {}},
        {"src": "images/asd199.png", "hotspots": {}},
        {"src": "images/asd200.png", "hotspots": {}},
        {"src": "images/asd201.png", "hotspots": {}},
        {"src": "images/asd202.png", "hotspots": {}},
        {"src": "images/asd203.png", "hotspots": {}},
        {"src": "images/asd204.png", "hotspots": {}},
        {"src": "images/asd205.png", "hotspots": {}},
        {"src": "images/asd206.png", "hotspots": {}},
        {"src": "images/asd207.png", "hotspots": {}},
        {"src": "images/asd208.png", "hotspots": {}},
        {"src": "images/asd209.png", "hotspots": {}},
        {"src": "images/asd210.png", "hotspots": {}},
        {"src": "images/asd211.png", "hotspots": {}},
        {"src": "images/asd212.png", "hotspots": {}},
        {"src": "images/asd213.png", "hotspots": {}},
        {"src": "images/asd214.png", "hotspots": {}},
        {"src": "images/asd215.png", "hotspots": {}},
        {"src": "images/asd216.png", "hotspots": {}},
        {"src": "images/asd217.png", "hotspots": {}},
        {"src": "images/asd218.png", "hotspots": {}},
        {"src": "images/asd219.png", "hotspots": {}},
        {"src": "images/asd220.png", "hotspots": {}},
        {"src": "images/asd221.png", "hotspots": {}},
        {"src": "images/asd222.png", "hotspots": {}},
        {"src": "images/asd223.png", "hotspots": {}},
        {"src": "images/asd224.png", "hotspots": {}},
        {"src": "images/asd225.png", "hotspots": {}},
        {"src": "images/asd226.png", "hotspots": {}},
        {"src": "images/asd227.png", "hotspots": {}},
        {"src": "images/asd228.png", "hotspots": {}},
        {"src": "images/asd229.png", "hotspots": {}},
        {"src": "images/asd230.png", "hotspots": {}},
        {"src": "images/asd231.png", "hotspots": {}},
        {"src": "images/asd232.png", "hotspots": {}},
        {"src": "images/asd233.png", "hotspots": {}},
        {"src": "images/asd234.png", "hotspots": {}},
        {"src": "images/asd235.png", "hotspots": {}},
        {"src": "images/asd236.png", "hotspots": {}},
        {"src": "images/asd237.png", "hotspots": {}},
        {"src": "images/asd238.png", "hotspots": {}},
        {"src": "images/asd239.png", "hotspots": {}},
        {"src": "images/asd240.png", "hotspots": {}},
        {"src": "images/asd241.png", "hotspots": {}},
        {"src": "images/asd242.png", "hotspots": {}},
        {"src": "images/asd243.png", "hotspots": {}},
        {"src": "images/asd244.png", "hotspots": {}},
        {"src": "images/asd245.png", "hotspots": {}},
        {"src": "images/asd246.png", "hotspots": {}},
        {"src": "images/asd247.png", "hotspots": {}},
        {"src": "images/asd248.png", "hotspots": {}},
        {"src": "images/asd249.png", "hotspots": {}},
        {"src": "images/asd250.png", "hotspots": {}}
    ]
};

//for maximum compatiblity, assign the data to 1. common named variable, 2. product - specific named variable

var RotationData_33 = productRotationData_1471761633144;
var RotationData = productRotationData_1471761633144;